version: "3.8"

services:
  notes-app-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
